version: '3.9'
services:
  mongo-db:
    container_name: mongo-db
    image: mongo:latest
    ports:
      - "49153:49153"
    environment:
      - MONGO_INITDB_DATABASE=plenna
      - mongo_init_host=mongo-db


    
  web:
    container_name: web
    build: .
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    ports:
      - "3000:3000"
    expose:
      - "3000"


